{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "artillery-load-testing.serviceAccountName" . }}
  labels:
    {{- include "artillery-load-testing.labels" . | nindent 4 }}
{{- end }}